baseurl = "https://vaneyckt.io"
languageCode = "en-us"
title = "vaneyckt.io"
theme = "hyde"
copyright = "Tom Van Eyck"

[Author]
	name = "Tom Van Eyck"

[Permalinks]
	blog = "/:year/:month/:filename/"

[Taxonomies]
	topic = "topics"

[params]
	description = "notes to my future self"
	mail = "mailto:tomvaneyck@gmail.com"
	github = "https://github.com/vaneyckt"
	rss = "https://vaneyckt.io/index.xml"
